### ISSUE TITLE
Aspect Ratio Issues

### ISSUE THREAD

**Issue by ramseys1990** [nicolomantini/Influencer-bot#3]
```
Request return 400 error!
{'message': "Uploaded image isn't in an allowed aspect ratio", 'status': 'fail'}
posted!!

```

It appears that the bot is grabbing images that do not fit Instagram aspect ratio requirements.  I haven't looked into the API that you're using yet to work on a solution to it but I assume you can use something like Pillow/PIL to resize images on the fly but could run into some issues with skewing the image.  How are you currently getting around this?

**Comment by nicolomantini** [comment]
Thanks for the comment! Yes there is a missing control for the aspect ratio. K thought about searching a new image in case of wrong aspect ratio, but what you proposed can probably work better!

**Comment by ramseys1990** [comment]
It must be square for instagram, correct?

**Comment by nicolomantini** [comment]
I believe here there the answer?.

https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI/ImageUtils.py
